"""Generate and patch the Android project. One tool, run by CI and by hand.

Take 16. The apk workflow job had never been executed anywhere — the exact
landmine-35/36 shape that bit takes 12 and 13. This tool IS the apk build's
first half; the workflow calls it, and it was first proven by running it in a
container until a real APK came out.

What it does, idempotently:
  1. writes package.json + capacitor.config.json (region-agnostic app identity)
  2. npm install (Capacitor core/cli/android + Geolocation + Haptics)
  3. npx cap add android (only when android/ is absent)
  4. patches what Capacitor's template does not know this app needs:
     - manifest permissions: fine/coarse location, wake lock, vibrate
     - MainActivity: FLAG_KEEP_SCREEN_ON — a nav screen that sleeps mid-trail
       is a safety failure, not a UX nit
     - fold configChanges: density added to Capacitor's defaults (landmine 7 —
       the Z Fold 7 changes density when it folds; without it Android restarts
       the activity and the WebView, dropping the ride state)
     - release signing from signing/apex.keystore (generated here if absent)
     - launcher icons, generated by tools/icon.py (legacy + adaptive)

The keystore is COMMITTED, deliberately. Tradeoff, stated plainly: anyone with
the repo can sign an update that installs over this app. For a personal
sideloaded tool that is acceptable, and the alternative — a fresh debug key per
CI run — means every new take refuses to install over the last one. Revisit
before any public distribution (AGENDA A21).
"""
import json, os, re, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
APP_ID = "com.sergeantslabs.apex"
APP_NAME = "APEX ORV"
KS = os.path.join(ROOT, "signing", "apex.keystore")
KS_PASS = "apexoffroad"        # committed on purpose — see module docstring


def run(cmd, **kw):
    print("  $ " + " ".join(cmd))
    r = subprocess.run(cmd, cwd=kw.pop("cwd", ROOT), **kw)
    if r.returncode:
        sys.exit(f"{cmd[0]} failed ({r.returncode})")


def write_if_changed(path, content):
    if os.path.exists(path) and open(path).read() == content:
        return False
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    open(path, "w").write(content)
    return True


def npm_configs():
    pkg = """{
  "name": "apex-offroad",
  "private": true,
  "version": "1.0.0",
  "description": "Offline ORV trail navigation for Michigan riding areas",
  "dependencies": {
    "@capacitor/android": "^7.0.0",
    "@capacitor/core": "^7.0.0",
    "@capacitor/geolocation": "^7.0.0",
    "@capacitor/haptics": "^7.0.0",
    "@capacitor/share": "^7.0.0",
    "@capacitor/device": "^7.0.0"
  },
  "devDependencies": {
    "@capacitor/cli": "^7.0.0",
    "puppeteer": "^25.0.0"
  }
}
"""
    cap = """{
  "appId": "%s",
  "appName": "%s",
  "webDir": "www",
  "server": { "androidScheme": "https" },
  "android": { "allowMixedContent": false }
}
""" % (APP_ID, APP_NAME)
    # Never clobber a package.json that already has what we need: this template
    # silently dropped puppeteer, so tools/render.mjs — the check that found the
    # blank map — could not run from a fresh clone (take 25).
    pj = os.path.join(ROOT, "package.json")
    a = False
    if os.path.exists(pj):
        cur = json.load(open(pj))
        want = json.loads(pkg)
        merged = dict(cur)
        for k in ("dependencies", "devDependencies"):
            m = dict(cur.get(k, {}))
            m.update(want.get(k, {}))
            merged[k] = m
        for k in ("name", "private", "version", "description"):
            merged.setdefault(k, want[k])
        if merged != cur:
            open(pj, "w").write(json.dumps(merged, indent=2) + "\n")
            a = True
    else:
        a = write_if_changed(pj, pkg)
    b = write_if_changed(os.path.join(ROOT, "capacitor.config.json"), cap)
    print(f"  package.json {'written' if a else 'current'}, "
          f"capacitor.config.json {'written' if b else 'current'}")


def scaffold():
    if not os.path.isdir(os.path.join(ROOT, "node_modules", "@capacitor")):
        run(["npm", "install", "--no-audit", "--no-fund"])
    else:
        print("  node_modules current")
    if not os.path.isdir(os.path.join(ROOT, "android")):
        run(["npx", "cap", "add", "android"])
    else:
        run(["npx", "cap", "sync", "android"])


def patch_strings():
    """The launcher label lives in strings.xml, which `cap add` writes ONCE and
    `cap sync` never revisits. Renaming the app in capacitor.config.json alone
    changes it everywhere except the home screen — the only place the rider
    actually reads it (take 38)."""
    p = os.path.join(ROOT, "android", "app", "src", "main", "res",
                     "values", "strings.xml")
    if not os.path.exists(p):
        return
    s = open(p).read()
    out = re.sub(r'(<string name="(?:app_name|title_activity_main)">)[^<]*(</string>)',
                 lambda m: m.group(1) + APP_NAME + m.group(2), s)
    if out != s:
        open(p, "w").write(out)
        print(f"  strings.xml: app_name -> {APP_NAME}")
    else:
        print("  strings.xml: current")


def patch_manifest():
    mf = os.path.join(ROOT, "android", "app", "src", "main", "AndroidManifest.xml")
    s = open(mf).read()
    orig = s
    perms = ["android.permission.ACCESS_FINE_LOCATION",
             "android.permission.ACCESS_COARSE_LOCATION",
             "android.permission.WAKE_LOCK",
             "android.permission.VIBRATE"]
    add = "".join(f'    <uses-permission android:name="{p}" />\n'
                  for p in perms if p not in s)
    if add:
        s = s.replace("</manifest>", add + "</manifest>")
    m = re.search(r'android:configChanges="([^"]+)"', s)
    if m and "density" not in m.group(1):
        s = s.replace(m.group(0),
                      f'android:configChanges="{m.group(1)}|density"')
    if s != orig:
        open(mf, "w").write(s)
    have = [p.rsplit(".", 1)[1] for p in perms if p in s]
    cc = re.search(r'android:configChanges="([^"]+)"', s).group(1)
    print(f"  manifest: {', '.join(have)}; configChanges={cc}")
    for need in ("screenSize", "smallestScreenSize", "screenLayout", "density"):
        if need not in cc:
            sys.exit(f"manifest configChanges missing {need} — fold-unsafe")


def patch_mainactivity():
    p = os.path.join(ROOT, "android", "app", "src", "main", "java",
                     *APP_ID.split("."), "MainActivity.java")
    s = open(p).read()
    if "FLAG_KEEP_SCREEN_ON" in s:
        print("  MainActivity: keep-screen-on current")
        return
    s = s.replace("import com.getcapacitor.BridgeActivity;",
                  "import android.os.Bundle;\n"
                  "import android.view.WindowManager;\n"
                  "import com.getcapacitor.BridgeActivity;")
    s = s.replace("public class MainActivity extends BridgeActivity {}",
                  "public class MainActivity extends BridgeActivity {\n"
                  "    @Override\n"
                  "    public void onCreate(Bundle savedInstanceState) {\n"
                  "        super.onCreate(savedInstanceState);\n"
                  "        // A navigation screen that sleeps mid-trail is a safety\n"
                  "        // failure. The battery cost is accepted and measured.\n"
                  "        getWindow().addFlags(\n"
                  "            WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);\n"
                  "    }\n"
                  "}")
    open(p, "w").write(s)
    print("  MainActivity: keep-screen-on added")


def keystore():
    if os.path.exists(KS):
        print("  keystore: present")
        return
    os.makedirs(os.path.dirname(KS), exist_ok=True)
    run(["keytool", "-genkeypair", "-v", "-keystore", KS,
         "-storetype", "PKCS12", "-alias", "apex",
         "-keyalg", "RSA", "-keysize", "2048", "-validity", "10000",
         "-storepass", KS_PASS, "-keypass", KS_PASS,
         # The COMMITTED keystore's cert reads CN=APEX Off-road and must stay
         # that way — it is what every installed build is signed against. This
         # dname only applies if the keystore is ever regenerated, which would
         # break update continuity regardless (AGENDA A21).
         "-dname", "CN=APEX Off-road, O=SergeantSlabs, C=US"],
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    print("  keystore: generated signing/apex.keystore")


def patch_signing():
    bg = os.path.join(ROOT, "android", "app", "build.gradle")
    s = open(bg).read()
    if "APEX-SIGNING" in s:
        print("  build.gradle: signing current")
        return
    s = s.replace("android {", """android {
    // APEX-SIGNING — committed keystore, tradeoff recorded in tools/android.py
    signingConfigs {
        release {
            storeFile file("../../signing/apex.keystore")
            storePassword "%s"
            keyAlias "apex"
            keyPassword "%s"
        }
    }""" % (KS_PASS, KS_PASS), 1)
    s = re.sub(r"(buildTypes\s*\{\s*release\s*\{)",
               r"\1\n            signingConfig signingConfigs.release", s, 1)
    open(bg, "w").write(s)
    print("  build.gradle: release signing wired")


if __name__ == "__main__":
    print("── android scaffold")
    npm_configs()
    scaffold()
    print("── patches")
    patch_strings()
    patch_manifest()
    patch_mainactivity()
    keystore()
    patch_signing()
    # Icons are generated, never committed as binaries — one source of truth
    # and no hand steps (landmine 32).
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    import icon
    icon.build()
    print("android/ ready — build with: cd android && ./gradlew assembleRelease")
